-- MySQL Script generated by MySQL Workbench
-- Thu May  7 13:17:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `hospital_db` ;

-- -----------------------------------------------------
-- Table `hospital_db`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`patient` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `phone_number` VARCHAR(30) NULL DEFAULT NULL,
  `insured` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`department` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_department_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`room` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(20) NOT NULL,
  `type` ENUM('ICU', 'GENERAL', 'SURGERY', 'RECOVERY', 'PRIVATE') NOT NULL,
  `capacity` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `occupied` TINYINT(1) NOT NULL DEFAULT '0',
  `department_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_room_number` (`room_number` ASC) VISIBLE,
  INDEX `fk_room_department` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital_db`.`department` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`admission` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `admitted_at` DATETIME NOT NULL,
  `discharged_at` DATETIME NULL DEFAULT NULL,
  `reason` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admission_patient` (`patient_id` ASC) VISIBLE,
  INDEX `fk_admission_room` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_admission_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patient` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_admission_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `hospital_db`.`room` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`blood_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`blood_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_blood_type_label` (`label` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`medical_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`medical_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `created_date` DATE NOT NULL,
  `blood_type_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_medical_record_patient` (`patient_id` ASC) VISIBLE,
  INDEX `fk_medical_record_blood_type` (`blood_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_medical_record_blood_type`
    FOREIGN KEY (`blood_type_id`)
    REFERENCES `hospital_db`.`blood_type` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medical_record_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`allergy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`allergy` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `medical_record_id` BIGINT UNSIGNED NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_allergy_medical_record` (`medical_record_id` ASC) VISIBLE,
  CONSTRAINT `fk_allergy_medical_record`
    FOREIGN KEY (`medical_record_id`)
    REFERENCES `hospital_db`.`medical_record` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`doctor` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `specialization` VARCHAR(100) NOT NULL,
  `available` TINYINT(1) NOT NULL DEFAULT '1',
  `department_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_department` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital_db`.`department` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`appointment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `doctor_id` BIGINT UNSIGNED NOT NULL,
  `scheduled_at` DATETIME NOT NULL,
  `status` ENUM('SCHEDULED', 'DONE', 'CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_patient` (`patient_id` ASC) VISIBLE,
  INDEX `fk_appointment_doctor` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospital_db`.`doctor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_appointment_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patient` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`payment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `admission_id` BIGINT UNSIGNED NOT NULL,
  `issued_date` DATE NOT NULL,
  `total_amount` DECIMAL(12,2) NOT NULL,
  `paid_amount` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `paid` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_payment_patient` (`patient_id` ASC) VISIBLE,
  INDEX `fk_payment_admission` (`admission_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_admission`
    FOREIGN KEY (`admission_id`)
    REFERENCES `hospital_db`.`admission` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patient` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`prescription` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `doctor_id` BIGINT UNSIGNED NOT NULL,
  `issued_date` DATE NOT NULL,
  `instructions` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prescription_patient` (`patient_id` ASC) VISIBLE,
  INDEX `fk_prescription_doctor` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescription_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospital_db`.`doctor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prescription_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patient` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`prescription_medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`prescription_medication` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prescription_id` BIGINT UNSIGNED NOT NULL,
  `medication_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_presc_med_prescription` (`prescription_id` ASC) VISIBLE,
  CONSTRAINT `fk_presc_med_prescription`
    FOREIGN KEY (`prescription_id`)
    REFERENCES `hospital_db`.`prescription` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`staff` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(80) NOT NULL,
  `last_name` VARCHAR(80) NOT NULL,
  `role` ENUM('NURSE', 'RECEPTIONIST', 'TECHNICIAN', 'ADMIN', 'PORTER') NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `hire_date` DATE NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_staff_department` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital_db`.`department` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
