-- MySQL Script generated by MySQL Workbench
-- Fri May  8 22:17:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospital_db` ;

-- -----------------------------------------------------
-- Table `hospital_db`.`medical_clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`medical_clinics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `total_rooms` BIGINT NULL DEFAULT NULL,
  `occupied_rooms` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`departments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `medical_clinics_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_medical_clinics_idx` (`medical_clinics_id` ASC) VISIBLE,
  CONSTRAINT `fk_departments_medical_clinics`
    FOREIGN KEY (`medical_clinics_id`)
    REFERENCES `hospital_db`.`medical_clinics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`rooms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(20) NOT NULL,
  `type` ENUM('ICU', 'GENERAL', 'SURGERY', 'RECOVERY', 'PRIVATE') NOT NULL,
  `capacity` BIGINT NOT NULL,
  `occupied` TINYINT(1) NOT NULL DEFAULT '0',
  `departments_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rooms_departments1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_rooms_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `hospital_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`patients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `insured` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`admissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`admissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `admitted_at` DATETIME NOT NULL,
  `discharged_at` DATETIME NULL DEFAULT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  `rooms_id` BIGINT NOT NULL,
  `patients_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admissions_rooms1_idx` (`rooms_id` ASC) VISIBLE,
  INDEX `fk_admissions_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_admissions_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `hospital_db`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admissions_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `hospital_db`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`medical_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`medical_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_date` DATE NOT NULL,
  `blood_type` ENUM('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE') NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `patients_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medical_records_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_medical_records_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `hospital_db`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`allergies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`allergies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `medical_records_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_allergies_medical_records1_idx` (`medical_records_id` ASC) VISIBLE,
  CONSTRAINT `fk_allergies_medical_records1`
    FOREIGN KEY (`medical_records_id`)
    REFERENCES `hospital_db`.`medical_records` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`doctors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `specialization` VARCHAR(255) NULL DEFAULT NULL,
  `available` TINYINT(1) NOT NULL DEFAULT '1',
  `departments_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctors_departments1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctors_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `hospital_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`appointments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `scheduled_at` DATETIME NOT NULL,
  `status` ENUM('SCHEDULED', 'DONE', 'CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
  `notes` TEXT NULL DEFAULT NULL,
  `doctors_id` BIGINT NOT NULL,
  `patients_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointments_doctors1_idx` (`doctors_id` ASC) VISIBLE,
  INDEX `fk_appointments_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_doctors1`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `hospital_db`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `hospital_db`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`payments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `issued_date` DATE NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `paid_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `paid` TINYINT(1) NOT NULL DEFAULT '0',
  `admissions_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_admissions1_idx` (`admissions_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_admissions1`
    FOREIGN KEY (`admissions_id`)
    REFERENCES `hospital_db`.`admissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`prescriptions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `issued_date` DATE NOT NULL,
  `instructions` TEXT NULL DEFAULT NULL,
  `doctors_id` BIGINT NOT NULL,
  `patients_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prescriptions_doctors1_idx` (`doctors_id` ASC) VISIBLE,
  INDEX `fk_prescriptions_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescriptions_doctors1`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `hospital_db`.`doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescriptions_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `hospital_db`.`patients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`prescription_medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`prescription_medications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `medication_name` VARCHAR(255) NOT NULL,
  `dosage` VARCHAR(100) NULL DEFAULT NULL,
  `frequency` VARCHAR(100) NULL DEFAULT NULL,
  `prescriptions_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prescription_medications_prescriptions1_idx` (`prescriptions_id` ASC) VISIBLE,
  CONSTRAINT `fk_prescription_medications_prescriptions1`
    FOREIGN KEY (`prescriptions_id`)
    REFERENCES `hospital_db`.`prescriptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`staff` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `role` ENUM('NURSE', 'RECEPTIONIST', 'TECHNICIAN') NOT NULL,
  `hire_date` DATE NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `departments_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_departments1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `hospital_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
